Repository isa-zip/isa.zip-backend, pull requests merged in 2024-02, with the labels that each got.

#27 [refactor] : 도로명 주소 입력시 도로명, 지번 , 우편번호 반환
  src/main/java/backend/zip/config/AddressConfig.java
  src/main/java/backend/zip/controller/broker/BrokerItemController.java
  src/main/java/backend/zip/domain/broker/BrokerItem.java
  src/main/java/backend/zip/domain/broker/BrokerOption.java
  src/main/java/backend/zip/dto/brokeritem/request/AddBrokerItemAddressRequest.java
  src/main/java/backend/zip/dto/brokeritem/response/AddressResponse.java
  src/main/java/backend/zip/dto/brokeritem/response/BrokerItemAddressByDongResponse.java
  src/main/java/backend/zip/dto/brokeritem/response/BrokerItemAddressResponse.java
  src/main/java/backend/zip/dto/brokeritem/response/BrokerItemOptionResponse.java
  src/main/java/backend/zip/dto/brokeritem/response/BrokerItemResponse.java
  src/main/java/backend/zip/service/broker/BrokerItemOptionServiceImpl.java
  src/main/java/backend/zip/service/broker/BrokerItemSaveService.java
  src/main/java/backend/zip/service/broker/BrokerItemSaveServiceImpl.java
  src/main/java/backend/zip/service/map/AddressService.java
  src/main/java/backend/zip/service/map/AddressServiceImpl.java
Labels: refactor

#29 [feat] : 매물 수정하기, 매물 삭제하기 구현 완료
  src/main/java/backend/zip/controller/broker/BrokerItemController.java
  src/main/java/backend/zip/domain/broker/BrokerItem.java
  src/main/java/backend/zip/domain/broker/BrokerOption.java
  src/main/java/backend/zip/domain/item/ItemContent.java
  src/main/java/backend/zip/dto/brokeritem/request/AddBrokerItemDetailsRequest.java
  src/main/java/backend/zip/dto/brokeritem/response/BrokerItemAddressResponse.java
  src/main/java/backend/zip/dto/brokeritem/response/BrokerItemDetailResponse.java
  src/main/java/backend/zip/dto/brokeritem/response/BrokerItemOptionResponse.java
  src/main/java/backend/zip/dto/brokeritem/response/BrokerItemResponse.java
  src/main/java/backend/zip/repository/broker/BrokerItemImageRepository.java
  src/main/java/backend/zip/repository/broker/BrokerItemRepository.java
  src/main/java/backend/zip/repository/broker/option/BrokerDealTypeRepository.java
  src/main/java/backend/zip/repository/broker/option/BrokerExtraFilterRepository.java
  src/main/java/backend/zip/repository/broker/option/BrokerFloorRepository.java
  src/main/java/backend/zip/repository/broker/option/BrokerInternalFacilityRepository.java
  src/main/java/backend/zip/repository/broker/option/BrokerManagementOptionRepository.java
  src/main/java/backend/zip/service/broker/BrokerItemAddressService.java
  src/main/java/backend/zip/service/broker/BrokerItemAddressServiceImpl.java
  src/main/java/backend/zip/service/broker/BrokerItemDetailService.java
  src/main/java/backend/zip/service/broker/BrokerItemDetailServiceImpl.java
  src/main/java/backend/zip/service/broker/BrokerItemOptionService.java
  src/main/java/backend/zip/service/broker/BrokerItemOptionServiceImpl.java
  src/main/java/backend/zip/service/broker/BrokerItemSaveServiceImpl.java
  src/main/java/backend/zip/service/broker/BrokerItemService.java
  src/main/java/backend/zip/service/broker/BrokerItemServiceImpl.java
Labels: feature, refactor

#32 Feature/schedule#26
  src/main/java/backend/zip/controller/ScheduleController.java
  src/main/java/backend/zip/domain/schedule/Schedule.java
  src/main/java/backend/zip/dto/schedule/request/AddScheduleRequest.java
  src/main/java/backend/zip/dto/schedule/request/UpdateScheduleRequest.java
  src/main/java/backend/zip/dto/schedule/response/ScheduleResponse.java
  src/main/java/backend/zip/repository/ScheduleRepository.java
  src/main/java/backend/zip/service/ScheduleService.java
  src/main/java/backend/zip/service/ScheduleServiceImpl.java
Labels: feature

#37 [isa-zip/isa.zip-backend] Pull request opened: #2 [feat] : 공인중개사 입장에서 유저요청 지역별 개수 조회 & 지역별 요청 모아보기(동별 요청 전체조회)
  src/main/java/backend/zip/controller/UserItemController.java
  src/main/java/backend/zip/domain/user/options/UserDealType.java
  src/main/java/backend/zip/domain/user/options/UserExtraFilter.java
  src/main/java/backend/zip/domain/user/options/UserFloor.java
  src/main/java/backend/zip/domain/user/options/UserInternalFacility.java
  src/main/java/backend/zip/domain/user/options/UserManagementOption.java
  src/main/java/backend/zip/domain/user/options/UserRoomSize.java
  src/main/java/backend/zip/domain/user/options/UserRoomType.java
  src/main/java/backend/zip/dto/useritem/response/UserItemAddressResponse.java
  src/main/java/backend/zip/dto/useritem/response/UserItemByDongResponse.java
  src/main/java/backend/zip/dto/useritem/response/UserItemDongCountResponse.java
  src/main/java/backend/zip/dto/useritem/response/UserItemOptionResponse.java
  src/main/java/backend/zip/dto/useritem/response/UserItemResponse.java
  src/main/java/backend/zip/repository/UserItemRepository.java
  src/main/java/backend/zip/service/userItem/UserItemService.java
  src/main/java/backend/zip/service/userItem/UserItemServiceImpl.java
Labels: feature

#55 [feat] : 공인중개사가 가지고 있는 매물 중 '동'으로 필터링 된 것만 올리기 구현
  src/main/java/backend/zip/controller/broker/BrokerItemListController.java
  src/main/java/backend/zip/dto/brokeritem/response/BrokerItemOptionResponse.java
  src/main/java/backend/zip/dto/brokeritem/response/BrokerItemResponse.java
  src/main/java/backend/zip/repository/broker/BrokerItemRepository.java
  src/main/java/backend/zip/service/brokeritem/BrokerItemShowService.java
  src/main/java/backend/zip/service/brokeritem/BrokerItemShowServiceImpl.java
Labels: :sparkles: feature

#57 [refactor] : 매칭 테이블에 동 칼럼 추가
  src/main/java/backend/zip/domain/match/Matching.java
Labels: :recycle: refactor

#58 [feat] : 매칭 후보 등록 api 구현 완료
  src/main/java/backend/zip/controller/broker/BrokerItemListController.java
  src/main/java/backend/zip/controller/matching/MatchController.java
  src/main/java/backend/zip/domain/match/Matching.java
  src/main/java/backend/zip/dto/brokeritem/response/BrokerItemResponse.java
  src/main/java/backend/zip/dto/match/request/BrokerItemIdRequest.java
  src/main/java/backend/zip/dto/match/response/MatchItemResponse.java
  src/main/java/backend/zip/service/MatchService.java
  src/main/java/backend/zip/service/MatchServiceImpl.java
  src/main/java/backend/zip/service/match/MatchService.java
  src/main/java/backend/zip/service/match/MatchServiceImpl.java
Labels: :sparkles: feature

#61 [feat] : 매물 매칭 완료 상태로 변경 및 매칭 매물 전체 조회
  src/main/java/backend/zip/controller/matching/MatchController.java
  src/main/java/backend/zip/domain/enums/MatchStatus.java
  src/main/java/backend/zip/domain/match/Matching.java
  src/main/java/backend/zip/domain/match/Review.java
  src/main/java/backend/zip/dto/match/response/MatchItemListResponse.java
  src/main/java/backend/zip/dto/match/response/MatchStatusResponse.java
  src/main/java/backend/zip/global/exception/match/MatchingException.java
  src/main/java/backend/zip/global/status/ErrorStatus.java
  src/main/java/backend/zip/service/match/MatchService.java
  src/main/java/backend/zip/service/match/MatchServiceImpl.java
Labels: :sparkles: feature

#63 [fix] : 충돌 해결
  src/main/java/backend/zip/controller/EventController.java
  src/main/java/backend/zip/controller/schedule/EventController.java
  src/main/java/backend/zip/controller/schedule/ScheduleController.java
  src/main/java/backend/zip/domain/schedule/Event.java
  src/main/java/backend/zip/dto/schedule/request/AddEventRequest.java
  src/main/java/backend/zip/dto/schedule/request/UpdateEventRequest.java
  src/main/java/backend/zip/dto/schedule/response/EventResponse.java
  src/main/java/backend/zip/repository/schedule/EventRepository.java
  src/main/java/backend/zip/repository/schedule/ScheduleRepository.java
  src/main/java/backend/zip/service/EventService.java
  src/main/java/backend/zip/service/ScheduleServiceImpl.java
  src/main/java/backend/zip/service/schedule/EventService.java
  src/main/java/backend/zip/service/schedule/EventServiceImpl.java
  src/main/java/backend/zip/service/schedule/ScheduleService.java
  src/main/java/backend/zip/service/schedule/ScheduleServiceImpl.java
Labels: :bug: bug, :recycle: refactor

#64 [feat] : 매칭 상태 변경 범용화
  src/main/java/backend/zip/controller/matching/MatchController.java
  src/main/java/backend/zip/dto/match/response/MatchItemAllByUserResponse.java
  src/main/java/backend/zip/service/match/MatchService.java
  src/main/java/backend/zip/service/match/MatchServiceImpl.java
Labels: :sparkles: feature

#65 [feat] : 사용자 매칭, 공인중개사 매칭 api 전부 구현 완료
  src/main/java/backend/zip/controller/broker/BrokerItemListController.java
  src/main/java/backend/zip/controller/matching/MatchController.java
  src/main/java/backend/zip/domain/enums/MatchStatus.java
  src/main/java/backend/zip/domain/match/Matching.java
  src/main/java/backend/zip/domain/match/Review.java
  src/main/java/backend/zip/dto/brokeritem/response/BrokerItemResponse.java
  src/main/java/backend/zip/dto/match/request/BrokerItemIdRequest.java
  src/main/java/backend/zip/dto/match/response/MatchItemAllByUserResponse.java
  src/main/java/backend/zip/dto/match/response/MatchItemListResponse.java
  src/main/java/backend/zip/dto/match/response/MatchItemResponse.java
  src/main/java/backend/zip/dto/match/response/MatchStatusResponse.java
  src/main/java/backend/zip/global/exception/match/MatchingException.java
  src/main/java/backend/zip/global/status/ErrorStatus.java
  src/main/java/backend/zip/repository/MatchRepository.java
  src/main/java/backend/zip/service/match/MatchService.java
  src/main/java/backend/zip/service/match/MatchServiceImpl.java
Labels: :sparkles: feature

#70 Fix/schedule#68
  src/main/java/backend/zip/controller/schedule/EventController.java
  src/main/java/backend/zip/controller/schedule/ScheduleController.java
  src/main/java/backend/zip/domain/schedule/Event.java
  src/main/java/backend/zip/service/schedule/EventService.java
  src/main/java/backend/zip/service/schedule/EventServiceImpl.java
  src/main/java/backend/zip/service/schedule/ScheduleServiceImpl.java
Labels: :bug: bug, :sparkles: feature, :recycle: refactor

#72 [refactor] : 매물 아이템을 반환 dto 수정 및 가격 데이터 필드 수정
  src/main/java/backend/zip/controller/broker/BrokerItemController.java
  src/main/java/backend/zip/controller/broker/BrokerItemListController.java
  src/main/java/backend/zip/domain/broker/options/BrokerDealType.java
  src/main/java/backend/zip/domain/broker/options/BrokerManagementOption.java
  src/main/java/backend/zip/dto/brokeritem/request/AddBrokerItemOptionsRequest.java
  src/main/java/backend/zip/dto/brokeritem/response/BrokerItemAddressResponse.java
  src/main/java/backend/zip/dto/brokeritem/response/BrokerItemDetailResponse.java
  src/main/java/backend/zip/dto/brokeritem/response/BrokerItemOptionResponse.java
  src/main/java/backend/zip/dto/brokeritem/response/BrokerItemResponse.java
  src/main/java/backend/zip/dto/brokeritem/response/BrokerItemStatusResponse.java
  src/main/java/backend/zip/dto/brokeritem/response/ItemContentResponse.java
  src/main/java/backend/zip/dto/brokeritem/response/ItemImageResponse.java
  src/main/java/backend/zip/dto/match/response/MatchItemListResponse.java
Labels: :recycle: refactor

#74 [fix] #73
  src/main/java/backend/zip/controller/UserItemController.java
  src/main/java/backend/zip/dto/useritem/response/UserItemByDongResponse.java
  src/main/java/backend/zip/repository/UserItemRepository.java
  src/main/java/backend/zip/service/userItem/UserItemService.java
  src/main/java/backend/zip/service/userItem/UserItemServiceImpl.java
Labels: :bug: bug

#76 [feature] 예외 처리 기능 추가
  src/main/java/backend/zip/controller/schedule/EventController.java
  src/main/java/backend/zip/controller/schedule/ScheduleController.java
  src/main/java/backend/zip/global/exception/schedule/DuplicatedScheduleException.java
  src/main/java/backend/zip/global/exception/schedule/EventNotFoundException.java
  src/main/java/backend/zip/global/exception/schedule/ScheduleNotFoundException.java
  src/main/java/backend/zip/global/status/ErrorStatus.java
  src/main/java/backend/zip/service/schedule/EventServiceImpl.java
  src/main/java/backend/zip/service/schedule/ScheduleService.java
  src/main/java/backend/zip/service/schedule/ScheduleServiceImpl.java
Labels: :bug: bug, :sparkles: feature, :recycle: refactor

#77 [refactor][fix] : 유저사이드매칭조회 리스펀스정리 및 0개 매칭 조회안되는거 수정
  src/main/java/backend/zip/dto/match/response/MatchItemAllByUserResponse.java
  src/main/java/backend/zip/repository/UserItemRepository.java
  src/main/java/backend/zip/service/match/MatchServiceImpl.java
Labels: :bug: bug, :recycle: refactor

#78 [refactor] : 유저사이드매칭조회 추가 리스펀스정리
  src/main/java/backend/zip/domain/user/options/UserDealType.java
  src/main/java/backend/zip/dto/brokeritem/response/BrokerItemNoAddressResponse.java
  src/main/java/backend/zip/dto/match/response/MatchItemAllByUserResponse.java
Labels: :recycle: refactor

#79 [refactor] : post users/items 의 인자값 도로명주소->동이름으로 변경
  src/main/java/backend/zip/controller/UserItemController.java
  src/main/java/backend/zip/domain/user/UserItem.java
  src/main/java/backend/zip/dto/useritem/response/UserItemAddressResponse.java
  src/main/java/backend/zip/dto/useritem/response/UserItemResponse.java
  src/main/java/backend/zip/repository/UserItemRepository.java
  src/main/java/backend/zip/service/map/AddressService.java
  src/main/java/backend/zip/service/map/AddressServiceImpl.java
  src/main/java/backend/zip/service/userItem/UserItemService.java
  src/main/java/backend/zip/service/userItem/UserItemServiceImpl.java
Labels: :recycle: refactor

#82 유저매칭완료시 공인중개사는 요청조회 못하게 하는 기능구현
  src/main/java/backend/zip/controller/matching/MatchController.java
  src/main/java/backend/zip/domain/enums/MatchStatus.java
  src/main/java/backend/zip/domain/enums/RoomSize.java
  src/main/java/backend/zip/domain/user/UserItem.java
  src/main/java/backend/zip/service/match/MatchServiceImpl.java
  src/main/java/backend/zip/service/userItem/UserItemServiceImpl.java
Labels: :sparkles: feature, :recycle: refactor

#85 [feat] : 매물 탭 메인화면 위도, 경도에 따른 반경 2km 매물 아이템
  src/main/java/backend/zip/controller/itemtab/ItemTabController.java
  src/main/java/backend/zip/dto/main/request/CurrentLocationRequest.java
  src/main/java/backend/zip/dto/main/response/BrokerItemListResponseOfMain.java
  src/main/java/backend/zip/repository/broker/BrokerItemByCurrentLocationRepository.java
  src/main/java/backend/zip/service/brokeritem/BrokerItemShowService.java
  src/main/java/backend/zip/service/brokeritem/BrokerItemShowServiceImpl.java
Labels: :sparkles: feature

#89 Feature/docker#88
  Dockerfile
  src/main/java/backend/zip/service/userItem/UserItemOptionServiceImpl.java
  src/test/java/backend/zip/ZipApplicationTests.java
Labels: :sparkles: feature, :recycle: refactor

#93 [refactor] : 매물매칭상태변경 관련 수정사항들
  src/main/java/backend/zip/controller/matching/MatchController.java
  src/main/java/backend/zip/domain/match/Matching.java
  src/main/java/backend/zip/dto/match/request/UpdateMatchingStatusRequest.java
  src/main/java/backend/zip/repository/MatchRepository.java
  src/main/java/backend/zip/service/match/MatchServiceImpl.java
Labels: :bug: bug, :recycle: refactor

#95 Fix/schedule#94
  src/main/java/backend/zip/dto/schedule/request/AddScheduleRequest.java
  src/main/java/backend/zip/dto/schedule/request/UpdateEventRequest.java
  src/main/java/backend/zip/dto/schedule/request/UpdateScheduleRequest.java
  src/main/java/backend/zip/dto/schedule/response/EventResponse.java
  src/main/java/backend/zip/dto/schedule/response/ScheduleResponse.java
  src/main/java/backend/zip/global/exception/schedule/DateNotFoundException.java
  src/main/java/backend/zip/global/status/ErrorStatus.java
  src/main/java/backend/zip/service/schedule/EventServiceImpl.java
  src/main/java/backend/zip/service/schedule/ScheduleServiceImpl.java
Labels: :bug: bug
